version: "3.8"

services:
  web:
    image: monishkha/notes-app:latest
    container_name: web_cont

    ports:
      - "8080:8000"

    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"

    env_file:
      - .env

    restart: always
